In [1]:
import numpy as np
from numpy import linalg

# 1. Создаем случайную квадратную матрицу 3x3
matrix = np.random.rand(3, 3)
print("Исходная матрица:")
print(matrix)

# 2. Находим определитель этой матрицы
determinant = linalg.det(matrix)
print("Определитель матрицы:", determinant)

# 3. Находим обратную матрицу (если существует, иначе выводим сообщение, что матрица вырождена)
try:
    inverse_matrix = linalg.inv(matrix)
    print("Обратная матрица:")
    print(inverse_matrix)
except linalg.LinAlgError:
    print("Матрица вырождена (не имеет обратной матрицы).")


Исходная матрица:
[[0.84612765 0.66258712 0.19005331]
 [0.69594645 0.78850319 0.14111315]
 [0.67709174 0.55180887 0.46140761]]
Определитель матрицы: 0.06401343572201536
Обратная матрица:
[[ 4.46709156 -3.13761681 -0.88040714]
 [-3.52376705  4.08861362  0.20100761]
 [-2.34106438 -0.285385    3.21884294]]
