In [1]:
import numpy as np

# 1. Создаем единичную матрицу размером 4x4
identity_matrix = np.eye(4)
print("Единичная матрица:")
print(identity_matrix)

# 2. Создаем диагональную матрицу размером 4x4 с диагональными элементами [5, 10, 15, 20]
diagonal_elements = [5, 10, 15, 20]
diagonal_matrix = np.diag(diagonal_elements)
print("Диагональная матрица:")
print(diagonal_matrix)

# 3. Находим сумму всех элементов каждой из этих матриц
identity_sum = np.sum(identity_matrix)
diagonal_sum = np.sum(diagonal_matrix)

print("Сумма элементов единичной матрицы:", identity_sum)
print("Сумма элементов диагональной матрицы:", diagonal_sum)

# 4. Сравниваем результаты
if identity_sum > diagonal_sum:
    print("Сумма элементов единичной матрицы больше.")
elif identity_sum < diagonal_sum:
    print("Сумма элементов диагональной матрицы больше.")
else:
    print("Суммы элементов матриц равны.")



Единичная матрица:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Диагональная матрица:
[[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]
Сумма элементов единичной матрицы: 4.0
Сумма элементов диагональной матрицы: 50
Сумма элементов диагональной матрицы больше.
