In [1]:
import numpy as np

# 1. Создаем две матрицы NumPy:
#    - Первая размером 2x3, заполненная случайными числами от 1 до 10
#    - Вторая размером 3x2, заполненная случайными числами от 1 до 10
matrix1 = np.random.randint(1, 11, size=(2, 3))
matrix2 = np.random.randint(1, 11, size=(3, 2))

print("Матрица 1:")
print(matrix1)
print("Матрица 2:")
print(matrix2)

# 2. Выполняем матричное умножение (@ или np.dot)
product_matrix = matrix1 @ matrix2  # Альтернативно: product_matrix = np.dot(matrix1, matrix2)

print("Матричное произведение:")
print(product_matrix)


Матрица 1:
[[7 3 7]
 [8 2 7]]
Матрица 2:
[[1 1]
 [7 2]
 [3 4]]
Матричное произведение:
[[49 41]
 [43 40]]
