In [1]:
import numpy as np

# Создание массива NumPy 3x3 с числами от 1 до 9
arr = np.arange(1, 10).reshape((3, 3))

# Умножение всех элементов массива на 2
arr = arr * 2

# Замена всех элементов больше 10 на 0
arr[arr > 10] = 0

# Вывод итогового массива
print(arr)

[[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]
