In [1]:
import numpy as np

# 1. Создаем две квадратные матрицы NumPy размером 3x3, заполненные случайными целыми числами от 1 до 20
matrix1 = np.random.randint(1, 21, size=(3, 3))
matrix2 = np.random.randint(1, 21, size=(3, 3))

print("Матрица 1:")
print(matrix1)
print("Матрица 2:")
print(matrix2)

# 2. Вычисляем их сумму
sum_matrix = matrix1 + matrix2
print("Сумма матриц:")
print(sum_matrix)

# 3. Вычисляем их разность
diff_matrix = matrix1 - matrix2
print("Разность матриц:")
print(diff_matrix)

# 4. Вычисляем их поэлементное произведение
elementwise_product = matrix1 * matrix2  # Или np.multiply(matrix1, matrix2)
print("Поэлементное произведение матриц:")
print(elementwise_product)



Матрица 1:
[[ 5 11  2]
 [13  1 16]
 [ 5 16 12]]
Матрица 2:
[[ 9  1 20]
 [16  3  7]
 [15 19 13]]
Сумма матриц:
[[14 12 22]
 [29  4 23]
 [20 35 25]]
Разность матриц:
[[ -4  10 -18]
 [ -3  -2   9]
 [-10  -3  -1]]
Поэлементное произведение матриц:
[[ 45  11  40]
 [208   3 112]
 [ 75 304 156]]
