In [1]:
import numpy as np

# 1. Создаем два массива NumPy размером 1x5, заполненные случайными числами от 0 до 50
arr1 = np.random.randint(0, 51, size=(1, 5))
arr2 = np.random.randint(0, 51, size=(1, 5))

print("Первый массив:")
print(arr1)
print("Второй массив:")
print(arr2)

# 2. Объединяем эти массивы в один двумерный массив (по строкам)
combined_arr = np.concatenate((arr1, arr2), axis=0)

print("Объединенный массив:")
print(combined_arr)

# 3. Разделяем полученный массив на два массива, каждый из которых содержит 5 элементов
arr3 = combined_arr[0]
arr4 = combined_arr[1]
# Alternatively, using split:
# arr3, arr4 = np.split(combined_arr, 2)
# arr3 = arr3[0]
# arr4 = arr4[0]


print("Первый подмассив (после разделения):")
print(arr3)
print("Второй подмассив (после разделения):")
print(arr4)


Первый массив:
[[35  7 20 45 22]]
Второй массив:
[[24  6  7 24 47]]
Объединенный массив:
[[35  7 20 45 22]
 [24  6  7 24 47]]
Первый подмассив (после разделения):
[35  7 20 45 22]
Второй подмассив (после разделения):
[24  6  7 24 47]
