In [1]:
import numpy as np

# 1. Создаем матрицу NumPy размером 4x4, содержащую случайные целые числа от 1 до 50
matrix = np.random.randint(1, 51, size=(4, 4))

# 2. Выводим исходную матрицу
print("Исходная матрица:")
print(matrix)

# 3. Выводим транспонированную матрицу
transposed_matrix = matrix.T  # Альтернативно: transposed_matrix = np.transpose(matrix)
print("Транспонированная матрица:")
print(transposed_matrix)

# 4. Выводим след матрицы (сумму элементов на главной диагонали)
matrix_trace = np.trace(matrix)
print("След матрицы:", matrix_trace)


Исходная матрица:
[[45 35 48 44]
 [17 12 19 19]
 [35 17 35 39]
 [35  9 41 31]]
Транспонированная матрица:
[[45 17 35 35]
 [35 12 17  9]
 [48 19 35 41]
 [44 19 39 31]]
След матрицы: 123
